name: Build iOS App

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version
      id: version
      run: |
        VERSION=$(grep '^version: ' pubspec.yaml | sed 's/version: //')
        
        # 分离版本号和构建号
        VERSION_NAME=$(echo $VERSION | cut -d'+' -f1)
        BUILD_NUMBER=$(echo $VERSION | cut -d'+' -f2)
        echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
        echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT

    - name: Build iOS Release
      uses: cedvdb/action-flutter-build-ios@v1
      with:
        # always use --export-options-plist=ios/GithubActionsExportOptions.plist
        build-cmd: flutter build ipa --release --export-options-plist=ios/GithubActionsExportOptions.plist
        certificate-base64: ${{ secrets.IOS_BUILD_CERTIFICATE_BASE64 }}
        certificate-password: ${{ secrets.IOS_BUILD_CERTIFICATE_PASSWORD }}
        provisioning-profile-base64: ${{ secrets.IOS_MOBILE_PROVISIONING_PROFILE_BASE64 }}
        keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}

    - name: Rename with version
      run: |
        ls build/ios/ipa/
        mv build/ios/ipa/*.ipa "build/growth-diary-${{ steps.version.outputs.version_name }}.ipa"
       
    - name: Upload IPA via SCP
      if: secrets.SSH_HOST != ''
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        source: "build/growth-diary-${{ steps.version.outputs.version_name }}.ipa"
        target: "${{ secrets.SSH_PATH }}/${{ secrets.ReleaseName != '' && format('{0}.ipa', secrets.ReleaseName) || format('growth-diary-{0}.ipa', steps.version.outputs.version_name) }}"    

    - name: Create Release Draft
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version_name }}
        release_name: Release v${{ steps.version.outputs.version_name }}
        draft: true
        prerelease: false

    - name: Upload IPA to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/growth-diary-${{ steps.version.outputs.version_name }}.ipa
        asset_name: growth-diary-${{ steps.version.outputs.version_name }}.ipa
        asset_content_type: application/octet-stream